import Head from 'next/head'
import HomeSlider from '../components/Home/HomeSlider/HomeSlider'
import Navbar from '../components/Navbar/Navbar'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Falcon Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/src/img/logo.svg" />
      </Head>
      <Navbar/>
      <HomeSlider/>
    </div>
  )
}
